# Use root/example as user/password credentials
version: "3.1"

services:
  portainer:
    image: portainer/portainer
    container_name: sdock_portainer_1
    restart: always
    networks:
      dev_network:
        ipv4_address: 172.20.0.3
    ports:
      - 9999:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  db-mysql-host:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-db-mysql-host
    image: brunojoao3/docker-sm:mysql-5.7.31
    container_name: db-mysql-5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./configs/mysql.cnf:/etc/mysql/conf.d/custom.cnf
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 789123
    networks:
      dev_network:
        ipv4_address: 172.20.0.4
    ports:
      - 3306:3306

  db-mysql8-host:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-db-mysql8-host
    container_name: db-mysql-8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./configs/mysql.cnf:/etc/mysql/conf.d/custom.cnf
      - mysql8_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 789123
    networks:
      dev_network:
        ipv4_address: 172.20.0.5
    ports:
      - 3307:3306

  php5.6:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php5-6
    image: brunojoao3/docker-sm:php-5.6-apache
    user: "root"
    container_name: php5-projects
    ports:
      - 900:900
      - 901:901
      - 902:902
      - 999:999
    volumes:
      - ../projects/supermonitor-hkm:/var/www/html/supermonitor-hkm
      - ../projects/supermonitor-hkm-jose:/var/www/html/supermonitor-hkm-jose
      - ../projects/supermonitor-smart:/var/www/html/supermonitor-smart
      - ../projects/gateway-payment-essentia:/var/www/html/gateway-payment-essentia
      - ./configs/php5.6/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./configs/php5.6/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./configs/php5.6/ports.conf:/etc/apache2/ports.conf
    command: >
      bash -c "a2enmod rewrite 
      && sed -i s/deb.debian.org/archive.debian.org/g /etc/apt/sources.list 
      && sed -i 's|security.debian.org|archive.debian.org/|g' /etc/apt/sources.list 
      && sed -i '/stretch-updates/d' /etc/apt/sources.list 
      && apt-get update 
      && apt-get -y install libxml2-dev zip unzip firebird-dev curl libjpeg-dev libpng-dev libfreetype6-dev libz-dev libtiff-dev git 
      && docker-php-ext-install interbase pdo pdo_mysql simplexml dom intl soap pdo_firebird gd 
      && chmod -R 777 /var/www/html 
      && curl --show-error https://getcomposer.org/installer -o /tmp/composer-setup.php 
      && php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer 
      && composer self-update --1 
      && sed -i 's/APACHE_RUN_GROUP:=www-data/APACHE_RUN_GROUP:=root/g' /etc/apache2/envvars 
      && apache2-foreground"
    networks:
      dev_network:
        ipv4_address: 172.20.0.6
    links:
      - db-mysql-host

  php7.4:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php7-4
    image: brunojoao3/docker-sm:php-7.4-apache
    user: "root"
    container_name: php7-projects
    ports:
      - 903:903
      - 904:904
    volumes:
      - ../projects/injetaveisadmin:/var/www/html/injetaveisadmin
      - ../projects/injetaveiscron:/var/www/html/injetaveiscron
      - ./configs/php7.4/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./configs/php7.4/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./configs/php7.4/ports.conf:/etc/apache2/ports.conf
    command: >
      bash -c "a2enmod rewrite 
      && apt-get update || true && apt-get -y install libxml2-dev zip unzip firebird-dev curl git 
      && docker-php-ext-install simplexml dom intl mysqli pdo pdo_mysql soap pdo_firebird 
      && chmod -R 777 /var/www/html 
      && curl --show-error https://getcomposer.org/installer -o /tmp/composer-setup.php
      && php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
      && composer self-update --1 
      && sed -i 's/APACHE_RUN_GROUP:=www-data/APACHE_RUN_GROUP:=root/g' /etc/apache2/envvars 
      && chown -R www-data:root /var/www/html/ 
      && apache2-foreground"
    networks:
      dev_network:
        ipv4_address: 172.20.0.7
    links:
      - db-mysql-host

  php8.1:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php8-1
    image: brunojoao3/docker-sm:php-8.1-apache
    user: "root"
    container_name: php8-projects
    ports:
      - 905:905
      - 906:906
      - 5173:5173
    volumes:
      - ../projects/gerenciador-compras:/var/www/html/gerenciador-compras
      - ../projects/selfcheckout:/var/www/html/selfcheckout
      - ./configs/php8.1/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./configs/php8.1/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./configs/php8.1/ports.conf:/etc/apache2/ports.conf
    command: >
      bash -c "a2enmod rewrite 
      && apt-get update 
      && apt-get -y install zlib1g-dev libxml2-dev libonig-dev libpng-dev zip unzip firebird-dev curl git 
      && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd 
      && curl --show-error https://getcomposer.org/installer -o /tmp/composer-setup.php 
      && php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer 
      && chmod -R 777 /var/www/html 
      && if [ ! -d /usr/local/node-v19.9.0-linux-x64 ]; then 
      curl -LO https://nodejs.org/dist/v19.9.0/node-v19.9.0-linux-x64.tar.xz 
      && tar -xvf node-v19.9.0-linux-x64.tar.xz 
      && mv node-v19.9.0-linux-x64 /usr/local/ 
      && ln -s /usr/local/node-v19.9.0-linux-x64/bin/node /usr/local/bin/node 
      && ln -s /usr/local/node-v19.9.0-linux-x64/bin/npm /usr/local/bin/npm; 
      fi
      && apache2-foreground"
    networks:
      dev_network:
        ipv4_address: 172.20.0.8
    links:
      - db-mysql8-host

  node-socket-sm:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-socket-sm
    image: brunojoao3/docker-sm:socket-sm-12.22.9
    user: "root"
    container_name: socket_sm
    working_dir: /home/node/app
    networks:
      dev_network:
        ipv4_address: 172.20.0.9
    ports:
      - 3003:3003
    volumes:
      - ../projects/node_server_sm:/home/node/app
    command: >
      bash -c "npm config set unsafe-perm true && npm install -f && npm install pm2 -g && pm2-runtime start index.js --watch"

  node-socket-injetaveis:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-socket-inj
    image: brunojoao3/docker-sm:socket-inj-12.22.9
    user: "root"
    container_name: socket_injetaveis
    working_dir: /home/node/app
    networks:
      dev_network:
        ipv4_address: 172.20.0.10
    ports:
      - 3004:3004
    volumes:
      - ../projects/node_server_injetaveis:/home/node/app
    command: >
      bash -c "npm config set unsafe-perm true && npm install -f && npm install pm2 -g && pm2-runtime start index.js --watch"

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - 9998:8080
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - dev_network

  cy-sm-hkm:
    container_name: cy-sm-hkm
    image: cypress/included:12.11.0
    working_dir: /e2e
    entrypoint: cypress open --project /e2e
    volumes:
      - ../projects/cy-sm-hkm:/e2e
      - /dev/shm:/dev/shm  # necessário para execução no modo headless
    links:
      - db-mysql-host
    command: ["cypress", "run"]
    networks:
      dev_network:
        ipv4_address: 172.20.0.11
        
volumes:
  mysql_data:
  mysql8_data:
  portainer_data:
  jenkins_home:

networks:
  dev_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
