# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./configs/mysql.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 789123
    ports:
      - 3349:3306

  php7.4:
    image: php:7.4-apache
    container_name: php7-projects
    ports:
      - 79:80
    volumes:
      - ../projects/injetaveis:/var/www/html/injetaveis
      # Espaço para outros projetos...
      - ./configs/php7.4/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./configs/php7.4/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    links:
      - db

  php5.6:
    image: php:5.6-apache
    container_name: php5-projects
    ports:
      - 80:80
    volumes:
      - ../projects/supermonitor-hkm:/var/www/html/supermonitor-hkm
      - ../projects/supermonitor-smart:/var/www/html/supermonitor-smart
      - ../projects/gpe:/var/www/html/gpe
      # Espaço para outros projetos...
      - ./configs/php5.6/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./configs/php5.6/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    links:
      - db
    
