# Use root/example as user/password credentials
version: "3.1"

services:
  portainer:
    image: portainer/portainer
    container_name: sdock_portainer_1
    restart: always
    networks:
      dev_network:
        ipv4_address: 172.20.0.3
    ports:
      - 9999:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  db-mysql8-host:
    image: mysql:8.0.32
    container_name: db-mysql-8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./configs/mysql.cnf:/etc/mysql/conf.d/custom.cnf
      - mysql8_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 789123
    networks:
      dev_network:
        ipv4_address: 172.20.0.5
    ports:
      - 3307:3306

  drupal9:
    image: drupal:9.5.7-apache
    user: "root"
    container_name: drupal9
    ports:
      - 5555:5555
    volumes:
      - ../projects/aldoimoveis:/var/www/html/aldoimoveis
      - ./configs/php8.1/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./configs/php8.1/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./configs/php8.1/ports.conf:/etc/apache2/ports.conf
    command: >
      bash -c "apt-get update 
      && curl --show-error https://getcomposer.org/installer -o /tmp/composer-setup.php 
      && php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer 
      && chmod -R 777 /var/www/html 
      && apache2-foreground"
    networks:
      dev_network:
        ipv4_address: 172.20.0.8
    links:
      - db-mysql8-host

volumes:
  mysql8_data:
  portainer_data:

networks:
  dev_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
