# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./configs/mysql.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 789123
    ports:
      - 3349:3306

  php7.4:
    image: php:7.4-apache
    container_name: php7-projects
    ports:
      - 8080:80
    volumes:
      - ../projects/injetaveisadmin:/var/www/html/injetaveisadmin
      # Espaço para outros projetos...
      - ./configs/php7.4/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./configs/php7.4/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    command: >
      bash -c "a2enmod rewrite 
      && apt-get update 
      && apt-get -y install libxml2-dev 
      && docker-php-ext-install simplexml 
      && docker-php-ext-enable simplexml 
      && docker-php-ext-install dom 
      && docker-php-ext-enable dom 
      && docker-php-ext-install intl 
      && docker-php-ext-enable intl 
      && docker-php-ext-install soap 
      && docker-php-ext-enable soap 
      && apache2-foreground"
    links:
      - db

  php5.6:
    image: php:5.6-apache
    container_name: php5-projects
    ports:
      - 80:80
    volumes:
      - ../projects/supermonitor-hkm:/var/www/html/supermonitor-hkm
      - ../projects/supermonitor-smart:/var/www/html/supermonitor-smart
      - ../projects/gateway-payment-essentia:/var/www/html/gateway-payment-essentia
      # Espaço para outros projetos...
      - ./configs/php5.6/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./configs/php5.6/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    command: >
      bash -c "a2enmod rewrite 
      && apt-get update 
      && apt-get -y install firebird-dev 
      && apt-get -y install libxml2-dev 
      && docker-php-ext-install interbase 
      && docker-php-ext-enable interbase 
      && docker-php-ext-install pdo_firebird 
      && docker-php-ext-enable pdo_firebird 
      && docker-php-ext-install simplexml 
      && docker-php-ext-enable simplexml 
      && docker-php-ext-install dom 
      && docker-php-ext-enable dom 
      && docker-php-ext-install intl 
      && docker-php-ext-enable intl 
      && docker-php-ext-install soap 
      && docker-php-ext-enable soap 
      && apache2-foreground"
    links:
      - db
    
