services:
  portainer:
    image: portainer/portainer-ce
    container_name: sdock_portainer_1
    networks:
      dev_network:
        ipv4_address: 172.20.0.3
    ports:
      - 9999:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  db-mysql-host:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-db-mysql-host
    image: brunojoao3/docker-sm:mysql-5.7.31
    container_name: db-mysql-5.7
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dockerfiles/configs/mysql.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      dev_network:
        ipv4_address: 172.20.0.4
    ports:
      - 3306:3306
    command: --ignore-db-dir=lost+found

  db-mysql8-host:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-db-mysql8-host
    image: brunojoao3/docker-sm:mysql-8.0.32
    container_name: db-mysql-8.0
    volumes:
      - mysql8_data:/var/lib/mysql
      - ./dockerfiles/configs/mysql8.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      dev_network:
        ipv4_address: 172.20.0.5
    ports:
      - 3307:3306

  php5.6:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php5-6
    image: brunojoao3/docker-sm:php-5.6-apache
    container_name: php5-projects
    ports:
      - 8080:8080
    volumes:
      - ./projects/supermonitor-hkm:/var/www/html/supermonitor-hkm
      - ./projects/supermonitor-smart:/var/www/html/supermonitor-smart
      - ./projects/gateway-payment-essentia:/var/www/html/gateway-payment-essentia
      - ./dockerfiles/configs/php5.6/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./dockerfiles/configs/php5.6/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./dockerfiles/configs/php5.6/ports.conf:/etc/apache2/ports.conf
    networks:
      dev_network:
        ipv4_address: 172.20.0.6
    links:
      - db-mysql-host
    extra_hosts:
      - "injetaveis.docker.local:172.20.0.7"
      - "injetaveis-cron.docker.local:172.20.0.7"
      - "gerenciador-compras.docker.local:172.20.0.9"

  php7.4:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php7-4
    image: brunojoao3/docker-sm:php-7.4-apache
    user: "root"
    container_name: php7-projects
    ports:
      - 8081:8081
    volumes:
      - ./projects/injetaveisadmin:/var/www/html/injetaveisadmin
      - ./projects/injetaveiscron:/var/www/html/injetaveiscron
      - ./projects/sm-tracking:/var/www/html/sm-tracking
      - ./dockerfiles/configs/php7.4/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./dockerfiles/configs/php7.4/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./dockerfiles/configs/php7.4/ports.conf:/etc/apache2/ports.conf
    networks:
      dev_network:
        ipv4_address: 172.20.0.7
    links:
      - db-mysql-host
    extra_hosts:
      - "sm-hkm.docker.local:172.20.0.6"
      - "sm-smart.docker.local:172.20.0.6"
      - "gpe.docker.local:172.20.0.6"
      - "gerenciador-compras.docker.local:172.20.0.9"

  php8.3-swoole:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php8-3-swoole
    privileged: true
    image: brunojoao3/docker-sm:php-8.3-swoole
    user: "root"
    container_name: "php8.3-swoole"
    volumes:
      - "./dockerfiles/configs/php8.3-swoole/php.ini:/usr/local/etc/php/conf.d/local.ini"
    network_mode: host

  php8.3-franken:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php8-3-franken
    image: brunojoao3/docker-sm:php-8.3-franken
    user: "root"
    container_name: "php8.3-franken"
    ports:
      - "8085:8085"
      - "5173:5173"
      - "5174:5174"
      - "5175:5175"
    volumes:
      - "./projects/blog-monitor:/var/www/blog-monitor"
      - "./projects/selfcheckout-pdf:/var/www/selfcheckout-pdf"
      - "./projects/selfcheckout:/var/www/selfcheckout"
      - "./projects/gerenciador-compras:/var/www/gerenciador-compras"
      - "./projects/ultramonitor:/var/www/ultramonitor"
      - "./projects/sku-keeper:/var/www/sku-keeper"
      - "./dockerfiles/configs/php8.3-franken/git-config.sh:/app/git-config.sh"
      - "./dockerfiles/configs/php8.3-franken/php.ini:/usr/local/etc/php/conf.d/local.ini"
      - "./dockerfiles/configs/php8.3-franken/Caddyfile:/etc/caddy/Caddyfile"
      - caddy_data:/data
      - caddy_config:/config
    networks:
      dev_network:
        ipv4_address: 172.20.0.10
    extra_hosts:
      - "injetaveis.docker.local:172.20.0.7"
      - "injetaveis-cron.docker.local:172.20.0.7"
      - "gerenciador-compras.local:172.20.0.10"
      - "sm-hkm.docker.local:172.20.0.6"
      - "sm-smart.docker.local:172.20.0.6"
      - "gpe.docker.local:172.20.0.6"
      - "selfcheckout.docker.local:172.20.0.10"
      - "sku-keeper.docker.local:172.20.0.11"
    command: sh -c "sh /app/git-config.sh && frankenphp run --config /etc/caddy/Caddyfile"

  node-socket-sm-hkm:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-socket-sm
    image: brunojoao3/docker-sm:socket-sm-12.22.9
    container_name: socket_sm_hkm
    networks:
      dev_network:
        ipv4_address: 172.20.0.50
    ports:
      - 3003:3003
    volumes:
      - ./projects/node_server_sm_hkm:/home/node/app
    command: sh -c "npm update && npm start index.js"

  node-socket-sm-smart:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-socket-sm
    image: brunojoao3/docker-sm:socket-sm-12.22.9
    container_name: socket_sm_smart
    networks:
      dev_network:
        ipv4_address: 172.20.0.51
    ports:
      - 3004:3004
    volumes:
      - ./projects/node_server_sm_smart:/home/node/app
    command: sh -c "npm update && npm start index.js"

  node-socket-injetaveis:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-socket-inj
    image: brunojoao3/docker-sm:socket-inj-12.22.9
    user: "root"
    container_name: socket_injetaveis
    networks:
      dev_network:
        ipv4_address: 172.20.0.52
    ports:
      - 3005:3005
    volumes:
      - ./projects/node_server_injetaveis:/home/node/app

  cy-sm-hkm:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-cypress
    container_name: cy-sm-hkm
    image: brunojoao3/docker-sm:cy-sm-hkm
    working_dir: /e2e
    environment:
      - DISPLAY=${DISPLAY} # espelha o valor do display do server (host) para o client (container)
    volumes:
      - ./projects/cy-sm-hkm:/e2e
      - /dev/shm:/dev/shm # necessário para execução no modo headless
    extra_hosts:
      - "sm-hkm.docker.local:172.20.0.6"
      - "sm-smart.docker.local:172.20.0.6"
      - "gpe.docker.local:172.20.0.6"
      - "gerenciador-compras.local:172.20.0.9"
    network_mode: host
    
  cache:
    image: redis:6.2-alpine
    container_name: cache
    ports:
      - '6382:6379'
    volumes: 
      - cache:/dataclear
    networks:
      dev_network:
        ipv4_address: 172.20.0.60

  smtp:
    platform: linux/x86_64
    image: mailhog/mailhog
    container_name: mailhog
    logging:
      driver: 'none'
    ports:
      - "8003:1025"
      - "8100:8025"
    networks:
      dev_network:
        ipv4_address: 172.20.0.70

volumes:
  mysql_data:
  mysql8_data:
  portainer_data:
  jenkins_home:
  caddy_data:
  caddy_config:
  cache:
    driver: local

networks:
  dev_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
