# Use root/example as user/password credentials
version: "3.1"

services:
  portainer:
    image: portainer/portainer-ce
    container_name: sdock_portainer_1
    restart: always
    networks:
      dev_network:
        ipv4_address: 172.20.0.3
    ports:
      - 9999:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  db-mysql-host:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-db-mysql-host
    image: brunojoao3/docker-sm:mysql-5.7.31
    container_name: db-mysql-5.7
    restart: always
    volumes:
      - ./dockerfiles/configs/mysql.cnf:/etc/mysql/conf.d/custom.cnf
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 789123
    networks:
      dev_network:
        ipv4_address: 172.20.0.4
    ports:
      - 3306:3306

  db-mysql8-host:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-db-mysql8-host
    container_name: db-mysql-8.0
    restart: always
    volumes:
      - ./dockerfiles/configs/mysql.cnf:/etc/mysql/conf.d/custom.cnf
      - mysql8_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 789123
    networks:
      dev_network:
        ipv4_address: 172.20.0.5
    ports:
      - 3307:3306

  php5.6:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php5-6
    image: brunojoao3/docker-sm:php-5.6-apache
    user: "root"
    container_name: php5-projects
    ports:
      - 9200:9200
      - 9201:9201
      - 9202:9202
      - 9203:9203
      - 9204:9204
      - 9205:9205
      - 9220:9220
      - 9221:9221
      - 9222:9222
      - 9223:9223
      - 9224:9224
      - 9225:9225
      - 9241:9241
      - 9242:9242
      - 9243:9243
      - 9244:9244
      - 9245:9245
    volumes:
      - ../projects/supermonitor-hkm-especial:/var/www/html/supermonitor-hkm-especial
      - ../projects/supermonitor-hkm-1:/var/www/html/supermonitor-hkm-1
      - ../projects/supermonitor-hkm-2:/var/www/html/supermonitor-hkm-2
      - ../projects/supermonitor-hkm-3:/var/www/html/supermonitor-hkm-3
      - ../projects/supermonitor-hkm-4:/var/www/html/supermonitor-hkm-4
      - ../projects/supermonitor-hkm-5:/var/www/html/supermonitor-hkm-5
      - ../projects/supermonitor-smart-especial:/var/www/html/supermonitor-smart-especial
      - ../projects/supermonitor-smart-1:/var/www/html/supermonitor-smart-1
      - ../projects/supermonitor-smart-2:/var/www/html/supermonitor-smart-2
      - ../projects/supermonitor-smart-3:/var/www/html/supermonitor-smart-3
      - ../projects/supermonitor-smart-4:/var/www/html/supermonitor-smart-4
      - ../projects/supermonitor-smart-5:/var/www/html/supermonitor-smart-5
      - ../projects/gateway-payment-essentia-1:/var/www/html/gateway-payment-essentia-1
      - ../projects/gateway-payment-essentia-2:/var/www/html/gateway-payment-essentia-2
      - ../projects/gateway-payment-essentia-3:/var/www/html/gateway-payment-essentia-3
      - ../projects/gateway-payment-essentia-4:/var/www/html/gateway-payment-essentia-4
      - ../projects/gateway-payment-essentia-5:/var/www/html/gateway-payment-essentia-5
      - ./dockerfiles/configs/php5.6/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./dockerfiles/configs/php5.6/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./dockerfiles/configs/php5.6/ports.conf:/etc/apache2/ports.conf
      - ./ssh-keys:/root/.ssh
    networks:
      dev_network:
        ipv4_address: 172.20.0.6
    links:
      - db-mysql-host

  php7.4:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php7-4
    image: brunojoao3/docker-sm:php-7.4-apache
    user: "root"
    container_name: php7-projects
    ports:
      - 9300:9300
      - 9320:9320
      - 9340:9340
    volumes:
      - ../projects/sm-tracking-1:/var/www/html/sm-tracking-1
      - ../projects/injetaveisadmin-1:/var/www/html/injetaveisadmin-1
      - ../projects/injetaveiscron-1:/var/www/html/injetaveiscron-1
      - ./dockerfiles/configs/php7.4/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./dockerfiles/configs/php7.4/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./dockerfiles/configs/php7.4/ports.conf:/etc/apache2/ports.conf
      - ./ssh-keys:/root/.ssh
    networks:
      dev_network:
        ipv4_address: 172.20.0.7
    links:
      - db-mysql-host

  php8.3:
    build:
      context: ./dockerfiles
      dockerfile: ./Dockerfile-php8-3-franken
    image: brunojoao3/docker-sm:php-8.3-franken-docker-in-docker
    user: "root"
    container_name: php8-franken
    ports:
      - 80:80
      - 443:443
      - 9401:9401
      - 9402:9402
      - 9403:9403
      - 9404:9404
      - 9405:9405
      - 9420:9420
      - 9421:9421
      - 9422:9422
      - 9423:9423
      - 9424:9424
      - 9425:9425
      - 9430:9430
      - 9440:9440
      - 5173:5173 #vite
      - 5174:5174 #vite
      - 5175:5175 #vite
    volumes:
      - "/var/www/projects/essentia-test-list:/var/www/html/essentia-test-list" #menu principal
      - "/var/www/projects/prateleira-infinita:/var/www/html/prateleira-infinita"
      - "/var/www/projects/gerenciador-compras-1:/var/www/html/gerenciador-compras-1"
      - "/var/www/projects/gerenciador-compras-2:/var/www/html/gerenciador-compras-2"
      - "/var/www/projects/gerenciador-compras-3:/var/www/html/gerenciador-compras-3"
      - "/var/www/projects/gerenciador-compras-4:/var/www/html/gerenciador-compras-4"
      - "/var/www/projects/gerenciador-compras-5:/var/www/html/gerenciador-compras-5"
      - "/var/www/projects/selfcheckout-especial:/var/www/html/selfcheckout-especial"
      - "/var/www/projects/selfcheckout-1:/var/www/html/selfcheckout-1"
      - "/var/www/projects/selfcheckout-2:/var/www/html/selfcheckout-2"
      - "/var/www/projects/selfcheckout-3:/var/www/html/selfcheckout-3"
      - "/var/www/projects/selfcheckout-4:/var/www/html/selfcheckout-4"
      - "/var/www/projects/selfcheckout-5:/var/www/html/selfcheckout-5"
      - "/var/www/projects/ultramonitor:/var/www/html/ultramonitor"
      - "./ssh-keys:/root/.ssh"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./dockerfiles/configs/php8.3-franken/git-config.sh:/app/git-config.sh"
      - "./dockerfiles/configs/php8.3-franken/php.ini:/usr/local/etc/php/conf.d/local.ini"
      - "./dockerfiles/configs/php8.3-franken/Caddyfile:/etc/caddy/Caddyfile"
      - caddy_data:/data
      - caddy_config:/config
    networks:
      dev_network:
        ipv4_address: 172.20.0.8
    links:
      - db-mysql8-host
      - db-mysql-host
    command: sh -c "sh /app/git-config.sh && frankenphp run --config /etc/caddy/Caddyfile"

  node-socket-sm-hkm:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-socket-sm
    image: brunojoao3/docker-sm:socket-sm-12.22.9
    user: "root"
    container_name: socket_sm_hkm
    working_dir: /home/node/app
    networks:
      dev_network:
        ipv4_address: 172.20.0.9
    ports:
      - 3003:3003
    volumes:
      - ../projects/node_server_sm_hkm:/home/node/app
    command: sh -c "npm update && npm start index.js"

  node-socket-sm-smart:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-socket-sm
    image: brunojoao3/docker-sm:socket-sm-12.22.9
    user: "root"
    container_name: socket_sm_smart
    working_dir: /home/node/app
    networks:
      dev_network:
        ipv4_address: 172.20.0.10
    ports:
      - 3004:3004
    volumes:
      - ../projects/node_server_sm_smart:/home/node/app
    command: sh -c "npm update && npm start index.js"

  node-socket-injetaveis:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-socket-inj
    image: brunojoao3/docker-sm:socket-inj-12.22.9
    user: "root"
    container_name: socket_injetaveis
    working_dir: /home/node/app
    networks:
      dev_network:
        ipv4_address: 172.20.0.11
    ports:
      - 3005:3003
    volumes:
      - ../projects/node_server_injetaveis:/home/node/app

  node-socket-sm-hkm-especial:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-socket-sm
    image: brunojoao3/docker-sm:socket-sm-12.22.9
    user: "root"
    container_name: socket_sm_hkm_especial
    environment:
      - DISPLAY=:0
    working_dir: /home/node/app
    networks:
      dev_network:
        ipv4_address: 172.20.0.12
    ports:
      - 3006:3006
    volumes:
      - ../projects/node_server_sm_hkm_especial:/home/node/app
    command: sh -c "npm update && npm start index.js"

  node-socket-sm-smart-especial:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-socket-sm
    image: brunojoao3/docker-sm:socket-sm-12.22.9
    user: "root"
    container_name: socket_sm_smart_especial
    working_dir: /home/node/app
    networks:
      dev_network:
        ipv4_address: 172.20.0.13
    ports:
      - 3007:3007
    volumes:
      - ../projects/node_server_sm_smart_especial:/home/node/app
    command: sh -c "npm update && npm start index.js"

  api-monitor:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-alpine-node
    image: brunojoao3/docker-sm:alpine-node
    container_name: api-monitor
    networks:
      dev_network:
        ipv4_address: 172.20.0.14
    ports:
      - 8090:8090
    volumes:
      - ../projects/api-monitor:/home/node/app/api-monitor
    command: sh -c "cd /home/node/app/api-monitor && node ace serve --watch"

  jenkins:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-jenkins-khan
    container_name: jenkins-khan
    image: brunojoao3/docker-sm:jenkins-khan
    user: root
    privileged: true
    ports:
      - 9998:8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      #- /usr/bin/docker:/usr/bin/docker
    networks:
      - dev_network

  cy-sm-hkm:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-cypress
    container_name: cy-sm-hkm
    image: brunojoao3/docker-sm:cy-sm-hkm
    environment:
      - DISPLAY=:0 # espelha o valor do display do server (host) para o client (container)
    working_dir: /e2e
    volumes:
      - ../projects/cy-sm-hkm:/e2e
      - /dev/shm:/dev/shm # necessário para execução no modo headless
      - ./ssh-keys:/root/.ssh
    command: >
      bash -c 'chmod 600 /root/.ssh/config && chmod 600 /root/.ssh/master-key-all && chown -R root:root /root/.ssh && sleep infinity'
    network_mode: host

  passbolt:
    image: passbolt/passbolt:latest
    container_name: passbolt
    environment:
      - DATASOURCES_DEFAULT_HOST=db-mysql8-host
      - DATASOURCES_DEFAULT_USERNAME=root
      - DATASOURCES_DEFAULT_PASSWORD=789123
      - DATASOURCES_DEFAULT_DATABASE=passbolt
      - DATASOURCES_DEFAULT_PORT=3306
      - APP_FULL_BASE_URL=http://192.168.66:9997
      - SECURED_PASSBOLT_API=http://192.168.66:9997
      - PASSBOLT_KEY_SERVER=https://keyserver.ubuntu.com/
      - GPG_SERVER=keyserver.ubuntu.com
      - GPG_SERVER_PORT=80
      - EMAIL_TRANSPORT_DEFAULT_CLASS_NAME=Smtp
      - EMAIL_DEFAULT_FROM=naoresponda@essentia.com.br
      - EMAIL_TRANSPORT_DEFAULT_HOST=smtp.gmail.com
      - EMAIL_TRANSPORT_DEFAULT_PORT=465
      - EMAIL_TRANSPORT_DEFAULT_TIMEOUT=30
      - EMAIL_TRANSPORT_DEFAULT_TLS=true
      - EMAIL_TRANSPORT_DEFAULT_USERNAME=naoresponda@essentia.com.br
      - EMAIL_TRANSPORT_DEFAULT_PASSWORD=${EMAIL_TRANSPORT_DEFAULT_PASSWORD}
    ports:
      - "9997:80"
    networks:
      dev_network:
        ipv4_address: 172.20.0.14
    depends_on:
      - db-mysql8-host
    links:
      - db-mysql8-host
    volumes:
      - passbolt_data:/var/www/passbolt

volumes:
  mysql_data:
  mysql8_data:
  portainer_data:
  jenkins_home:
  passbolt_data:
  caddy_data:
  caddy_config:

networks:
  dev_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
