# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:5.7.31
    container_name: db-1
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./configs/mysql.cnf:/etc/mysql/conf.d/custom.cnf
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 789123
    ports:
      - 3349:3306

  php7.4:
    image: php:7.4-apache
    container_name: php7-projects
    ports:
      - 8080:80
    volumes:
      - ../projects/injetaveisadmin:/var/www/html/injetaveisadmin
      # Espaço para outros projetos...
      - ./configs/php7.4/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./configs/php7.4/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      #- ./configs/php7.4/apache2.conf:/etc/apache2/apache2.conf
      - ./configs/php7.4/ports.conf:/etc/apache2/ports.conf
    command: > 
      bash -c "a2enmod rewrite 
      && apt-get update 
      && apt-get -y install libxml2-dev unzip firebird-dev 
      && docker-php-ext-install simplexml dom intl pdo_mysql soap pdo_firebird  
      && apache2-foreground 
      && chmod -R 777 /var/www/html 
      && curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php 
      && php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer 
      && composer self-update --1"
    links:
      - db
    extra_hosts:
    - "injetaveis.docker.local:127.0.0.1"

  php5.6:
    image: php:5.6-apache
    container_name: php5-projects
    ports:
      - 8081:80
    volumes:
      - ../projects/supermonitor-hkm:/var/www/html/supermonitor-hkm
      - ../projects/supermonitor-smart:/var/www/html/supermonitor-smart
      - ../projects/gateway-payment-essentia:/var/www/html/gateway-payment-essentia
      # Espaço para outros projetos...
      - ./configs/php5.6/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./configs/php5.6/000-default.conf:/etc/apache2/sites-enabled/000-default.conf 
      - ./configs/php5.6/ports.conf:/etc/apache2/ports.conf
      # - ./configs/php5.6/apache2.conf:/etc/apache2/apache2.conf 
    command: >
      bash -c "a2enmod rewrite 
      && apt-get update 
      && apt-get -y install libxml2-dev unzip firebird-dev 
      && docker-php-ext-install interbase pdo_mysql simplexml dom intl soap pdo_firebird interbase
      && apache2-foreground 
      && chmod -R 777 /var/www/html 
      && curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php 
      && php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer 
      && composer self-update --1"
    links:
      - db
    extra_hosts:
    - "sm-hkm.docker.local:127.0.0.1"
    - "sm-smart.docker.local:127.0.0.1"
    - "gpe.docker.local:127.0.0.1"
volumes:
  mysql_data:
