# Use root/example as user/password credentials
version: "3.1"

services:
  portainer:
    image: portainer/portainer-ce
    container_name: sdock_portainer_1
    restart: always
    networks:
      dev_network:
        ipv4_address: 172.20.0.3
    ports:
      - 9999:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  db-mysql-host:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-db-mysql-host
    image: brunojoao3/docker-sm:mysql-5.7.31
    container_name: db-mysql-5.7
    restart: always
    volumes:
      - ./dockerfiles/configs/mysql.cnf:/etc/mysql/conf.d/custom.cnf
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 789123
    networks:
      dev_network:
        ipv4_address: 172.20.0.4
    ports:
      - 3306:3306

  db-mysql8-host:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-db-mysql8-host
    container_name: db-mysql-8.0
    restart: always
    volumes:
      - ./dockerfiles/configs/mysql.cnf:/etc/mysql/conf.d/custom.cnf
      - mysql8_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 789123
    networks:
      dev_network:
        ipv4_address: 172.20.0.5
    ports:
      - 3307:3306

  php5.6:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php5-6
    image: brunojoao3/docker-sm:php-5.6-apache
    user: "root"
    container_name: php5-projects
    ports:
      - 9200:9200
      - 9201:9201
      - 9202:9202
      - 9220:9220
      - 9240:9240
    volumes:
      - ../projects/supermonitor-hkm-1:/var/www/html/supermonitor-hkm-1
      - ../projects/supermonitor-hkm-2:/var/www/html/supermonitor-hkm-2
      - ../projects/supermonitor-hkm-especial:/var/www/html/supermonitor-hkm-especial
      - ../projects/supermonitor-smart:/var/www/html/supermonitor-smart
      - ../projects/gateway-payment-essentia:/var/www/html/gateway-payment-essentia
      - ./dockerfiles/configs/php5.6/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./dockerfiles/configs/php5.6/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./dockerfiles/configs/php5.6/ports.conf:/etc/apache2/ports.conf
      - ./ssh-keys:/root/.ssh
    networks:
      dev_network:
        ipv4_address: 172.20.0.6
    links:
      - db-mysql-host

  php7.4:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php7-4
    image: brunojoao3/docker-sm:php-7.4-apache
    user: "root"
    container_name: php7-projects
    ports:
      - 9300:9300
      - 9320:9320
    volumes:
      - ../projects/injetaveisadmin:/var/www/html/injetaveisadmin
      - ../projects/injetaveiscron:/var/www/html/injetaveiscron
      - ./dockerfiles/configs/php7.4/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./dockerfiles/configs/php7.4/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./dockerfiles/configs/php7.4/ports.conf:/etc/apache2/ports.conf
      - ./ssh-keys:/root/.ssh
    networks:
      dev_network:
        ipv4_address: 172.20.0.7
    links:
      - db-mysql-host

  php8.1:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-php8-1
    image: brunojoao3/docker-sm:php-8.1-apache
    user: "root"
    container_name: php8-projects
    ports:
      - 9400:9400
      - 9401:9401
      - 9420:9420
      - 9421:9421
      - 9430:9430
      - 5173:5173 #vite 
      - 5174:5174 #vite 
      - 5175:5175 #vite 
    volumes:
      - ../projects/prateleira-infinita:/var/www/html/prateleira-infinita
      - ../projects/gerenciador-compras-1:/var/www/html/gerenciador-compras-1
      - ../projects/gerenciador-compras-2:/var/www/html/gerenciador-compras-2
      - ../projects/selfcheckout-especial:/var/www/html/selfcheckout-especial
      - ../projects/selfcheckout:/var/www/html/selfcheckout
      - ./dockerfiles/configs/php8.1/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./dockerfiles/configs/php8.1/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./dockerfiles/configs/php8.1/ports.conf:/etc/apache2/ports.conf
      - ./ssh-keys:/root/.ssh
    networks:
      dev_network:
        ipv4_address: 172.20.0.8
    links:
      - db-mysql8-host

  node-socket-sm-hkm:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-socket-sm
    image: brunojoao3/docker-sm:socket-sm-12.22.9
    user: "root"
    container_name: socket_sm_hkm
    working_dir: /home/node/app
    networks:
      dev_network:
        ipv4_address: 172.20.0.9
    ports:
      - 3003:3003
    volumes:
      - ../projects/node_server_sm_hkm:/home/node/app
    command: sh -c "npm update && pm2-runtimestart index.js --watch"

  node-socket-sm-smart:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-socket-sm
    image: brunojoao3/docker-sm:socket-sm-12.22.9
    user: "root"
    container_name: socket_sm_smart
    working_dir: /home/node/app
    networks:
      dev_network:
        ipv4_address: 172.20.0.10
    ports:
      - 3004:3004
    volumes:
      - ../projects/node_server_sm_smart:/home/node/app
    command: sh -c "npm update && pm2-runtimestart index.js --watch"

  node-socket-injetaveis:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-socket-inj
    image: brunojoao3/docker-sm:socket-inj-12.22.9
    user: "root"
    container_name: socket_injetaveis
    working_dir: /home/node/app
    networks:
      dev_network:
        ipv4_address: 172.20.0.11
    ports:
      - 3005:3003
    volumes:
      - ../projects/node_server_injetaveis:/home/node/app

  node-socket-sm-especial:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-socket-sm
    image: brunojoao3/docker-sm:socket-sm-12.22.9
    user: "root"
    container_name: socket_sm_especial
    working_dir: /home/node/app
    networks:
      dev_network:
        ipv4_address: 172.20.0.12
    ports:
      - 3006:3006
    volumes:
      - ../projects/node_server_sm_especial:/home/node/app
    command: sh -c "npm update && pm2-runtimestart index.js --watch"

  jenkins:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-jenkins-khan
    container_name: jenkins-khan
    image: brunojoao3/docker-sm:jenkins-khan
    user: root
    privileged: true
    ports:
      - 9998:8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      #- /usr/bin/docker:/usr/bin/docker
    networks:
      - dev_network

  cy-sm-hkm:
    container_name: cy-sm-hkm
    image: brunojoao3/docker-sm:cy-sm-hkm
    working_dir: /e2e
    volumes:
      - ../projects/cy-sm-hkm:/e2e
      - /dev/shm:/dev/shm # necessário para execução no modo headless
      - ./ssh-keys:/root/.ssh
    command: >
      bash -c 'chmod 600 /root/.ssh/config && chmod 600 /root/.ssh/master-key-all && chown -R root:root /root/.ssh && sleep infinity'
    network_mode: host

volumes:
  mysql_data:
  mysql8_data:
  portainer_data:
  jenkins_home:


networks:
  dev_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
