# Use root/example as user/password credentials
version: "3.1"

services:
  portainer:
    image: portainer/portainer
    container_name: sdock_portainer_1
    restart: always
    ports:
      - 9999:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  db-mysql-host:
    image: mysql:5.7.31
    container_name: db-mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./configs/mysql.cnf:/etc/mysql/conf.d/custom.cnf
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 789123
    ports:
      - 3306:3306
  php7.4:
    image: php:7.4-apache
    user: "root"
    container_name: php7-projects
    ports:
      - 8080:80
      - 9000:9000
    volumes:
      - ../projects/injetaveisadmin:/var/www/html/injetaveisadmin
      - ../projects/injetaveiscron:/var/www/html/injetaveiscron
      - ./configs/php7.4/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./configs/php7.4/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      #- ./configs/php7.4/apache2.conf:/etc/apache2/apache2.conf
      - ./configs/php7.4/ports.conf:/etc/apache2/ports.conf
      - ./configs/php7.4/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    command: >
      bash -c "a2enmod rewrite 
      && apt-get update 
      && apt-get -y install libxml2-dev zip unzip firebird-dev curl 
      && pecl install xdebug-3.1.6 || true
      && docker-php-ext-install simplexml dom intl mysqli pdo pdo_mysql soap pdo_firebird 
      && docker-php-ext-enable xdebug 
      && chmod -R 777 /var/www/html 
      && curl --show-error https://getcomposer.org/installer -o /tmp/composer-setup.php
      && php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
      && composer self-update --1 
      && sed -i 's/APACHE_RUN_GROUP:=www-data/APACHE_RUN_GROUP:=root/g' /etc/apache2/envvars 
      && apache2-foreground"
    links:
      - db-mysql-host
    extra_hosts:
      - "injetaveis.docker.local:127.0.0.1"

  php5.6:
    image: php:5.6-apache
    user: "root"
    container_name: php5-projects
    ports:
      - 8081:80
      - 9001:9001
    volumes:
      - ../projects/supermonitor-hkm:/var/www/html/supermonitor-hkm
      - ../projects/supermonitor-smart:/var/www/html/supermonitor-smart
      - ../projects/gateway-payment-essentia:/var/www/html/gateway-payment-essentia
      - ./configs/php5.6/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./configs/php5.6/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./configs/php5.6/ports.conf:/etc/apache2/ports.conf
      - ./configs/php5.6/status.conf:/etc/apache2/mods-enabled/status.conf
      - ./configs/php5.6/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      # - ./configs/php5.6/apache2.conf:/etc/apache2/apache2.conf
    command: >
      bash -c "a2enmod rewrite 
      && apt-get update 
      && apt-get -y install libxml2-dev zip unzip firebird-dev curl libjpeg-dev libpng-dev libfreetype6-dev libz-dev libtiff-dev 
      && pecl install xdebug-2.5.5 || true
      && docker-php-ext-install interbase pdo pdo_mysql simplexml dom intl soap pdo_firebird interbase gd 
      && docker-php-ext-enable xdebug 
      && chmod -R 777 /var/www/html 
      && curl --show-error https://getcomposer.org/installer -o /tmp/composer-setup.php 
      && php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer 
      && composer self-update --1 
      && sed -i 's/APACHE_RUN_GROUP:=www-data/APACHE_RUN_GROUP:=root/g' /etc/apache2/envvars 
      && apache2-foreground"
    links:
      - db-mysql-host
    extra_hosts:
      - "sm-hkm.docker.local:127.0.0.1"
      - "sm-smart.docker.local:127.0.0.1"
      - "gpe.docker.local:127.0.0.1"

  node-socket-sm:
    image: node:12.22.9
    user: "root"
    container_name: socket_sm
    working_dir: /home/node/app
    ports:
      - 3003:3003
    volumes:
      - ../projects/node_server_sm:/home/node/app
    command: >
      bash -c "npm config set unsafe-perm true && npm install -f && npm install pm2 -g && pm2-runtime start index.js --watch"

  node-socket-injetaveis:
    image: node:12.22.9
    user: "root"
    container_name: socket_injetaveis
    working_dir: /home/node/app
    ports:
      - 3004:3004
    volumes:
      - ../projects/node_server_injetaveis:/home/node/app
    command: >
      bash -c "npm config set unsafe-perm true && npm install -f && npm install pm2 -g && pm2-runtime start index.js --watch"

volumes:
  mysql_data:
  portainer_data:
