FROM --platform=linux/amd64 node:lts-bullseye

# Atualiza os pacotes do sistema
RUN apt-get update

# Atualiza o sistema e instala as dependências necessárias
RUN apt-get install -y \
    libgtk2.0-0 \
    libgtk-3-0 \
    libgbm-dev \
    libnotify-dev \
    libgconf-2-4 \
    libnss3 \
    libxss1 \
    libasound2 \
    libxtst6 \
    xauth \
    xvfb \
    chromium \
    firefox-esr

# Define o diretório de trabalho
WORKDIR /e2e

# Instala o Cypress usando npm
RUN npx cypress install

# Set XDG_RUNTIME_DIR and disable Vulkan warnings
ENV XDG_RUNTIME_DIR=/tmp/runtime-cypress
RUN mkdir -p /tmp/runtime-cypress && chmod 0700 /tmp/runtime-cypress
ENV MESA_VK_IGNORE_CONFORMANCE_WARNING=1

# Define o comando padrão do contêiner
CMD npx cypress open --browser chromium
