FROM --platform=linux/amd64 dunglas/frankenphp:00b1d0e4b674ee4cef9febbd1444180f7ff6ab41-php8.3.1
WORKDIR /var/www
RUN apt-get update \
    && apt-get -y install zip unzip firebird-dev curl libjpeg-dev libpng-dev git zlib1g-dev libonig-dev libssl-dev libevent-dev \
    && install-php-extensions \
        pdo_mysql \
        gd \
        mysqli \
        intl \
        zip \
        opcache \ 
    && curl --show-error https://getcomposer.org/installer -o /tmp/composer-setup.php \
    && php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && rm /tmp/composer-setup.php \
    && chmod -R 777 /var/www/html \
    && if [ ! -d /usr/local/node19 ]; then \
        curl -o /tmp/node19.tar.xz https://nodejs.org/dist/v19.9.0/node-v19.9.0-linux-x64.tar.xz \
        && tar -xvf /tmp/node19.tar.xz -C /tmp --strip-components=1 --one-top-level=node19 \
        && rm /tmp/node19.tar.xz \
        && mv /tmp/node19 /usr/local/ \
        && ln -s /usr/local/node19/bin/node /usr/local/bin/node \
        && ln -s /usr/local/node19/bin/npm /usr/local/bin/npm \
        && ln -s /usr/local/node19/bin/npx /usr/local/bin/npx; \
    fi 

CMD ["frankenphp", "run", "--config", "/etc/caddy/Caddyfile"]
