FROM --platform=linux/amd64 dunglas/frankenphp:00b1d0e4b674ee4cef9febbd1444180f7ff6ab41-php8.3.1
WORKDIR /var/www
RUN apt-get update \
    && apt-get -y install firebird-dev curl libjpeg-dev libpng-dev git zlib1g-dev libonig-dev libssl-dev libevent-dev \
    && install-php-extensions \
        pdo_mysql \
        gd \
        mysqli \
        intl \
        zip \
        opcache

CMD ["frankenphp", "run", "--config", "/etc/caddy/Caddyfile"]
