FROM --platform=linux/amd64 phpswoole/swoole:php8.3

RUN apt-get update \
      && apt-get -y install libxml2-dev zip unzip firebird-dev curl libjpeg-dev libpng-dev libfreetype6-dev libz-dev libtiff-dev git zlib1g-dev libonig-dev libssl-dev libevent-dev \
      && docker-php-ext-install \
      pdo_mysql \
      gd \
      mysqli \
      intl \
      opcache

WORKDIR /var/www
CMD ["php swoole-server/server.php"]
