FROM node:12.22.9

USER root

WORKDIR /home/node/app

RUN npm config set unsafe-perm true && \
    npm install -f && \
    npm install -g --unsafe-perm=true --allow-root pm2

EXPOSE 3003

CMD ["pm2-runtime","start","index.js","--watch"]