FROM --platform=linux/amd64 mysql:8.0.32

ENV MYSQL_ROOT_AUTH_PLUGIN=mysql_native_password
ENV MYSQL_ROOT_PASSWORD=789123
ENV TZ=America/Sao_Paulo

# Copiar o arquivo de configuração personalizado
COPY configs/mysql.cnf /etc/mysql/conf.d/custom.cnf
