FROM --platform=linux/amd64 dunglas/frankenphp:00b1d0e4b674ee4cef9febbd1444180f7ff6ab41-php8.3.1
WORKDIR /var/www
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get -y install zip unzip firebird-dev curl libjpeg-dev libpng-dev git zlib1g-dev libonig-dev libssl-dev libevent-dev ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils \
    && install-php-extensions \
        pdo_mysql \
        gd \
        mysqli \
        intl \
        zip \
        opcache \
    && curl --show-error https://getcomposer.org/installer -o /tmp/composer-setup.php \
    && php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && rm /tmp/composer-setup.php \
    && chmod -R 777 /var/www/html \
    && if [ ! -d /usr/local/node20 ]; then \
        curl -o /tmp/node20.tar.xz https://nodejs.org/dist/v20.9.0/node-v20.9.0-linux-x64.tar.xz \
        && tar -xvf /tmp/node20.tar.xz -C /tmp --strip-components=1 --one-top-level=node20 \
        && rm /tmp/node20.tar.xz \
        && mv /tmp/node20 /usr/local/ \
        && ln -s /usr/local/node20/bin/node /usr/local/bin/node \
        && ln -s /usr/local/node20/bin/npm /usr/local/bin/npm \
        && ln -s /usr/local/node20/bin/npx /usr/local/bin/npx; \
    fi \
    && npx puppeteer browsers install chrome

CMD ["frankenphp", "run", "--config", "/etc/caddy/Caddyfile"]
