FROM node:12.22.9

USER root

WORKDIR /home/node/app

RUN npm config set unsafe-perm true && \
    npm install -f && \
    npm install pm2 -g

EXPOSE 3004

CMD ["pm2-runtime", "start", "index.js", "--watch"]