FROM --platform=linux/amd64 php:8.1-apache

# Executar o comando
RUN a2enmod rewrite \
    && apt-get update \
    && apt-get -y install zlib1g-dev libxml2-dev libonig-dev libpng-dev zip unzip firebird-dev curl git \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd \
    && curl --show-error https://getcomposer.org/installer -o /tmp/composer-setup.php \
    && php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && rm /tmp/composer-setup.php \
    && chmod -R 777 /var/www/html \
    && if [ ! -d /usr/local/node19 ]; then \
        curl -o /tmp/node19.tar.xz https://nodejs.org/dist/v19.9.0/node-v19.9.0-linux-x64.tar.xz \
        && tar -xvf /tmp/node19.tar.xz -C /tmp --strip-components=1 --one-top-level=node19 \
        && rm /tmp/node19.tar.xz \
        && mv /tmp/node19 /usr/local/ \
        && ln -s /usr/local/node19/bin/node /usr/local/bin/node \
        && ln -s /usr/local/node19/bin/npm /usr/local/bin/npm \
        && ln -s /usr/local/node19/bin/npx /usr/local/bin/npx; \
    fi

CMD ["apache2-foreground"]

# Restante do Dockerfile...
