-- Creating the migrations table
CREATE TABLE MIGRATIONS
(
    VERSION VARCHAR(255) NOT NULL
);

-- Creating the table FC99999
CREATE TABLE FC99999
(
    SUBARGUM  VARCHAR(50) NOT NULL,
    ARGUMENTO VARCHAR(50) NOT NULL,
    PARAMETRO VARCHAR(50),
    DESCRPAR  VARCHAR(100)
);

-- Creating the table FC07000
CREATE TABLE FC07000
(
    CDCLI   INTEGER PRIMARY KEY,
    NOMECLI VARCHAR(100),
    DTNAS   DATE,
    NRCNPJ  VARCHAR(20),
    EMAIL   VARCHAR(100),
    EMAIL2  VARCHAR(100),
    NRINSCR VARCHAR(20),
    NRCPF   VARCHAR(20),
    UFRG    VARCHAR(2),
    TPDOC   VARCHAR(10),
    OBSPOT  VARCHAR(255)
);

-- Creating the table FC07A00
CREATE TABLE FC07A00
(
    CDOBS   VARCHAR(50) NOT NULL,
    TPLOCAL VARCHAR(50),
    OBS     VARCHAR(255),
    CDCLI   INTEGER,
    FOREIGN KEY (CDCLI) REFERENCES FC07000 (CDCLI)
);

-- Creating the table FC07200
CREATE TABLE FC07200
(
    CDCLI    INTEGER PRIMARY KEY,
    NRDDD    VARCHAR(10),
    NRTEL    VARCHAR(20),
    NRDDD2   VARCHAR(10),
    NRTEL2   VARCHAR(20),
    NRDDDFAX VARCHAR(10),
    NRFAX    VARCHAR(20),
    MUNIC    VARCHAR(100),
    UNFED    VARCHAR(2),
    ENDER    VARCHAR(255),
    ENDNR    VARCHAR(10),
    NRCEP    VARCHAR(10),
    ENDCP    VARCHAR(255),
    BAIRR    VARCHAR(100),
    FOREIGN KEY (CDCLI) REFERENCES FC07000 (CDCLI)
);

-- Creating the table FC04000
CREATE TABLE FC04000
(
    NRCRM   VARCHAR(10),
    UFCRM   VARCHAR(2),
    PFCRM   VARCHAR(2),
    NOMEMED VARCHAR(100),
    NRCEL   VARCHAR(20),
    TPTRAT  VARCHAR(50),
    PRIMARY KEY (NRCRM, UFCRM, PFCRM)
);

-- Creating the table FC04400
CREATE TABLE FC04400
(
    NRCRM  VARCHAR(10),
    UFCRM  VARCHAR(2),
    PFCRM  VARCHAR(2),
    NRTEL  VARCHAR(20),
    NRTEL2 VARCHAR(20),
    NRFAX  VARCHAR(20),
    PRIMARY KEY (NRCRM, UFCRM, PFCRM),
    FOREIGN KEY (NRCRM, UFCRM, PFCRM) REFERENCES FC04000 (NRCRM, UFCRM, PFCRM)
);

-- Creating the table FC08000
CREATE TABLE FC08000
(
    CDFUN   INTEGER PRIMARY KEY,
    NOMEFUN VARCHAR(100),
    USERID  VARCHAR(100)
);

-- Creating the table FC15000
CREATE TABLE FC15000
(
    CDFIL  INTEGER,
    NRORC  INTEGER,
    CDCLI  INTEGER,
    DTENTR DATE,
    NOMEPA VARCHAR(100),
    CDFUN  VARCHAR(10),
    VRRQU  NUMERIC(14, 2),
    VRDSC  NUMERIC(14, 2),
    PRIMARY KEY (CDFIL, NRORC),
    FOREIGN KEY (CDCLI) REFERENCES FC07000 (CDCLI)
);

-- Creating the table FC15100
CREATE TABLE FC15100
(
    CDFIL        INTEGER,
    NRORC        INTEGER,
    SERIEO       VARCHAR(10),
    PFCRM        VARCHAR(2),
    UFCRM        VARCHAR(2),
    NRCRM        VARCHAR(10),
    QTCONT       INTEGER,
    VRDSC        NUMERIC(14, 2),
    PRCOBR       NUMERIC(14, 2),
    PRREAL       NUMERIC(18, 2),
    CDCLI        INTEGER,
    DTENTR       DATE,
    CDFUNRE      INTEGER,
    CDFUNDG      INTEGER,
    NOMEPA       VARCHAR(100),
    VOLUME       NUMERIC(14, 2),
    TPFORMAFARMA VARCHAR(50),
    QTFOR        INTEGER,
    UNIVOL       VARCHAR(10),
    TITROT       VARCHAR(255),
    UNICONT      VARCHAR(10),
    TPCAP        VARCHAR(50),
    CDEMB        INTEGER,
    DTCAD        DATE,
    HRCAD        TIME,
    PRIMARY KEY (CDFIL, NRORC, SERIEO),
    FOREIGN KEY (CDFIL, NRORC) REFERENCES FC15000 (CDFIL, NRORC),
    FOREIGN KEY (CDCLI) REFERENCES FC07000 (CDCLI),
    FOREIGN KEY (CDFUNRE) REFERENCES FC08000 (CDFUN),
    FOREIGN KEY (CDFUNDG) REFERENCES FC08000 (CDFUN)
);

-- Creating the table FC03000
CREATE TABLE FC03000
(
    CDPRO        INTEGER PRIMARY KEY,
    DOMAX        NUMERIC(14, 2),
    UNIDM        VARCHAR(10),
    DOMAXD       NUMERIC(14, 2),
    UNIDMD       VARCHAR(10),
    PORTA        VARCHAR(20),
    DESCRPRD     VARCHAR(255),
    TPFORMAFARMA VARCHAR(50),
    DIASVAL      INTEGER,
    SETOR        VARCHAR(50),
    CDOBS        VARCHAR(50)
);

-- Creating the table FC15110
CREATE TABLE FC15110
(
    CDFIL        INTEGER,
    NRORC        INTEGER,
    SERIEO       VARCHAR(10),
    CDPRO        INTEGER,
    DESCR        VARCHAR(255),
    ITEMID       INTEGER,
    QUANT        NUMERIC(14, 2),
    UNIDA        VARCHAR(10),
    CDPRIN       INTEGER,
    TPCMP        VARCHAR(50),
    DTENTR       DATE,
    TPFORMAFARMA VARCHAR(50),
    PORTA        VARCHAR(20),
    PRIMARY KEY (CDFIL, NRORC, SERIEO, CDPRO),
    FOREIGN KEY (CDFIL, NRORC, SERIEO) REFERENCES FC15100 (CDFIL, NRORC, SERIEO),
    FOREIGN KEY (CDPRO) REFERENCES FC03000 (CDPRO)
);

-- Creating the table FC03200
CREATE TABLE FC03200
(
    CDSIN    INTEGER PRIMARY KEY,
    CDPRO    INTEGER,
    DESCRPRD VARCHAR(255),
    FOREIGN KEY (CDPRO) REFERENCES FC03000 (CDPRO)
);

-- Creating the necessary indexes
CREATE INDEX IDX_FC07A00_CDOBS ON FC07A00 (CDOBS);
CREATE INDEX IDX_FC07A00_CDCLI ON FC07A00 (CDCLI);
CREATE INDEX IDX_FC99999_SUBARGUM ON FC99999 (SUBARGUM);
CREATE INDEX IDX_FC99999_ARGUMENTO ON FC99999 (ARGUMENTO);
CREATE INDEX IDX_FC07200_CDCLI ON FC07200 (CDCLI);
